pr: none

trigger:
  branches:
    include:
      - main

variables:
  dockerRegistryServiceConnection: '480dd8f9-a634-47ee-b0a2-658206dfb459'
  imageRepository: 'nadeko'
  tag: '$(Build.BuildId)'

stages:
  - stage: build
    displayName: Build and push stage
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: "$(Build.SourcesDirectory)/Dockerfile"
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
                latest

  - stage: deployProd
    displayName: Deploy Prod
    dependsOn: build
    jobs:
      - deployment: deployProd
        pool: self-hosted-scale-set-02
        displayName: Deploy Prod
        environment: prod
        strategy:
          runOnce:
            deploy:
              steps:
                - task: Docker@2
                  displayName: Authenticate to docker registry
                  inputs:
                    command: login
                    containerRegistry: $(dockerRegistryServiceConnection)
                - script: |
                    COMPOSE_FILE=/apps/nadeko/docker-compose.yml
                    PROJECT=nadeko

                    docker compose -f $COMPOSE_FILE -p $PROJECT pull
                    docker compose -f $COMPOSE_FILE -p $PROJECT down
                    docker compose -f $COMPOSE_FILE -p $PROJECT up --force-recreate -d
                  env:
                    TAG: $(tag)
