name: Docker Image CI

on:
  workflow_dispatch:
  push:
      branches:
        - 'v4'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      dockerImage: eu.gcr.io/personalweb-279207/nadeko
    steps:
    - uses: actions/checkout@v2
    
    - name: Docker Build
      run: docker build -f ./Dockerfile -t "${{ env.dockerImage }}:build-${{ github.run_id }}" -t "${{ env.dockerImage }}:latest" .
    
    - name: Docker Login
      env:
        DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
      run: echo $DOCKER_PASSWORD | docker login -u _json_key --password-stdin https://eu.gcr.io
      
    - name: Docker Push
      run: docker image push --all-tags "${{ env.dockerImage }}"
